// assets/client/routes/start.tsx
import { useTranslation } from 'react-i18next';

export default function StartPage() {
  const { t } = useTranslation();

  return (
    <div className="custom-container no-transparency">
      <div className="custom-text-box">
        <h1 className="text-center my-2">{t('HOME.TITLE')}</h1>
        <p className="text-center my-2">{t('HOME.DESCRIPTION')}</p>
        <a href="/login" className="button" title="Login">
          {t('HOME.BUTTON')}
        </a>
      </div>
    </div>
  );
}

// apps/client/src/app/pages/start/start.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'money-sprouts-start',
    templateUrl: './start.component.html',
    styleUrls: ['./start.component.scss'],
})
export class StartComponent {
    constructor(private router: Router) {}
}

<money-sprouts-multilanguage></money-sprouts-multilanguage>
<div class="custom-container no-transparency">
    <div class="custom-text-box">
        <h1 class="home-title">{{ 'HOME.TITLE' | translate }}</h1>
        <p class="home-text">
            {{ 'HOME.DESCRIPTION' | translate }}
        </p>
        <a href="/login" class="button" title="Login">
            {{ 'HOME.BUTTON' | translate }}
        </a>
    </div>
</div>
