// assets/client/components/PageHeader.tsx
import LocaleSwitcher from '@/client/components/LocaleSwitcher';
import './PageHeader.scss';
import { useTranslation } from 'react-i18next';

interface Props {
  title?: string;
  isLoggedIn: boolean;
  backButtonTarget?: string;
}

export default function PageHeader({
  title,
  isLoggedIn,
  backButtonTarget,
}: Props) {
  const { t } = useTranslation();
  return (
    <>
      <nav className="navbar navbar-light bg-light">
        <div className="container-fluid d-flex justify-content-between align-items-center">
          <div className="d-flex justify-content-start align-items-center">
            {backButtonTarget ? (
              <a
                href={backButtonTarget}
                className="btn btn-link"
                title={t('PAGE_HEADER.BUTTONS.GO_TO_ACCOUNT_SELECTION')}
              >
                <img
                  src="/assets/images/go-back-arrow_small.png"
                  width={50}
                  height={50}
                  alt="Go back arrow"
                />
              </a>
            ) : (
              <div className="pseudo-element" />
            )}
          </div>

          <div className="d-flex justify-content-center">
            <div className="d-flex align-items-center">
              <div className="page-title navbar-text">{title}</div>
            </div>
          </div>

          <div className="d-flex justify-content-end align-items-center">
            <div>
              <LocaleSwitcher />
            </div>
            {isLoggedIn && (
              <a href="/logout" title={t('PAGE_HEADER.BUTTONS.LOGOUT')}>
                <img
                  src="/assets/images/logout-round-grey_small.png"
                  alt="logout button"
                  width={50}
                  height={50}
                  className="image-50x50"
                />
              </a>
            )}
          </div>
        </div>
      </nav>
    </>
  );
}

// apps/client/src/shared/page-header/page-header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { User, UserService } from '../../app/services/user.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'money-sprouts-page-header',
  templateUrl: './page-header.component.html',
  styleUrls: ['./page-header.component.scss'],
})
export class PageHeaderComponent implements OnInit {
  username: string;
  user$: Observable<User | null>;
  urlSegments: string;

  constructor(private router: Router, private settings: UserService) {}

  ngOnInit() {
    const urlSegments = this.router.url.split('/');
    this.username = urlSegments[1];
    this.user$ = this.settings.fetchUser(this.username);
  }

  backToDashboard() {
    if (this.urlSegments !== 'dashboard') {
      this.router.navigate([`${this.username}/dashboard`]);
    } else {
      return;
    }
  }

  backToSelection() {
    this.router.navigate(['userselection']);
  }

  get pageTitle(): string {
    const pageName = this.router.url.split('/')[2];
    switch (pageName) {
      case 'dashboard':
        return 'Dashboard';
      case 'overview':
        return 'Overview';
      case 'history':
        return 'History';
      case 'plan':
        return 'Plan';
      default:
        return '';
    }
  }
}

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <div *ngIf="urlSegment !== 'userselection'">
            <div class="d-flex align-items-center">
                <button
                    class="btn btn-link"
                    (click)="backToDashboard()"
                    title="Go to Dashboard">
                   
                    <div>
                        <div *ngIf="username === 'Thea'; else showMaleAvatar" >
                            <img src="assets/images/avatar_female.png" alt="avatar image Thea" style="width:50px; height:50px;" />
                        </div>
                        <ng-template #showMaleAvatar>
                            <img src="assets/images/avatar_male.png" alt="avatar image Robert" style="width:50px; height:50px;" />
                        </ng-template>
                    </div>
                </button>
                <button class="btn btn-link" (click)="backToSelection()" title="Go to User Selection">
                    <img src="assets/images/change-user_grey_small.png" alt="change user" title="Click to change user"/>
                </button>
            </div>
        </div>
        
        <div class="flex-grow-1 text-center">
            <span class="navbar-text">
                {{ pageTitle }}
            </span>
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-link" title="Logout">
                <img src="assets/images/logout-grey-small.png" alt="logout button" title="Logout"/>
            </button>
        </div>
    </div> 
</nav>
