// assets/client/components/account/plan/PlanExpenses.tsx
import { useTranslation } from 'react-i18next';
import { useParams } from 'react-router-dom';
import useApi from '@/client/hooks/useApi';
import { Account } from '@/client/interfaces/Account';
import './PlanExpenses.scss';

export default function PlanExpenses() {
  const { t, i18n } = useTranslation();
  const { id } = useParams();
  const { data: account, isLoading, error } = useApi<Account>(`accounts/${id}`);

  // { t('PLAN.TAB_SPENT.ERROR_MESSAGE.PRODUCT_INPUT')}
  // { t('PLAN.TAB_SPENT.ERROR_MESSAGE.AMOUNT_INPUT')}

  function calculate() {
    // if (this.fieldsAreEmpty(spendingForm)) {
    //   return;
    // } else if (spendingForm.valid) {
    //   const displayAmount = spendingForm.value.amount;
    //   const enteredAmount =
    //     this.formattingHelperService.germanFormatToNumber(
    //       displayAmount
    //     ) * 100;
    //   console.log('enteredAmount: ', enteredAmount);
    //   this.calculateAmount.emit(enteredAmount);
    //   this.icon = 'ℹ';
    //   this.message = 'PLAN.TAB_SPENT.MESSAGE_CONFIRM';
    // } else {
    //   this.icon = '⚠';
    //   this.message =
    //     'PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_1 ' +
    //     spendingForm.value.amount +
    //     ' PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_2 ' +
    //     spendingForm.value.title +
    //     ' PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_3';
    // }
  }

  function apply() {
    // if (this.fieldsAreEmpty(spendingForm)) {
    //   return;
    // } else if (spendingForm.valid) {
    //   const title = spendingForm.value.title;
    //   const enteredAmount = spendingForm.value.amount;
    //   const formattedAmount =
    //     this.formattingHelperService.germanFormatToNumber(
    //       enteredAmount
    //     );
    //   const amount = formattedAmount * -100;
    //   console.log('selected name & sum:', title, amount);
    //
    //   this.applyChanges.emit({ title, amount });
    //   this.icon = '✔';
    //   this.message = 'PLAN.TAB_SPENT.MESSAGE_SUCCESS';
    // } else {
    //   this.icon = '⚠';
    //   this.message = 'PLAN.TAB_SPENT.ERROR_MESSAGE.GENERAL';
    // }
  }

  return (
    <>
      <form className="form-container">
        <div className="form-group">
          <label className="name-label" htmlFor="title">
            {t('PLAN.TAB_SPENT.NAME_LABEL')}
          </label>
          <input
            className="name-input"
            type="text"
            id="title"
            name="title"
            required
            pattern="^[a-zA-Z\s0-9\-.]+$"
            title={t('PLAN.TAB_SPENT.INPUT_HINT.PRODUCT_INPUT')}
          />
        </div>

        <div className="form-group">
          <label className="amount-label" htmlFor="amount">
            {t('PLAN.TAB_SPENT.AMOUNT_LABEL')}
          </label>
          <input
            className="amount-input"
            type="text"
            id="amount"
            name="amount"
            required
            pattern="^\d+(?:,\d{1,2})?$"
            title={t('PLAN.TAB_SPENT.INPUT_HINT.AMOUNT_INPUT')}
          />
        </div>

        <div className="button-group--plan-page">
          <button className="button" type="submit" onClick={() => calculate()}>
            {t('PLAN.TAB_SPENT.BUTTON_LABEL.CALCULATE')}
          </button>
          <button className="button" type="submit" onClick={() => apply()}>
            {t('PLAN.TAB_SPENT.BUTTON_LABEL.SUBMIT')}
          </button>
        </div>
      </form>
    </>
  );
}

// apps/client/src/app/pages/plan/plan-expenses/plan-expenses.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { NgForm } from '@angular/forms';
import { FormattingHelperService } from '../../../services/formatting-helper.service';

@Component({
    selector: 'money-sprouts-plan-expenses',
    templateUrl: './plan-expenses.component.html',
    styleUrls: ['./plan-expenses.component.scss'],
})
export class PlanExpensesComponent {
    message: string | null = '';
    icon: string | null = null;

    @Output() calculateAmount = new EventEmitter<number>();
    @Output() applyChanges = new EventEmitter<{
        title: string;
        amount: number;
    }>();
    @Output() resetBalance = new EventEmitter<void>();

    constructor(public formattingHelperService: FormattingHelperService) {}

    calculate(spendingForm: NgForm) {
        if (this.fieldsAreEmpty(spendingForm)) {
            return;
        } else if (spendingForm.valid) {
            const displayAmount = spendingForm.value.amount;
            const enteredAmount =
                this.formattingHelperService.germanFormatToNumber(
                    displayAmount
                ) * 100;
            console.log('enteredAmount: ', enteredAmount);
            this.calculateAmount.emit(enteredAmount);
            this.icon = 'ℹ';
            this.message = 'PLAN.TAB_SPENT.MESSAGE_CONFIRM';
        } else {
            this.icon = '⚠';
            this.message =
                'PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_1 ' +
                spendingForm.value.amount +
                ' PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_2 ' +
                spendingForm.value.title +
                ' PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INVALID.PART_3';
        }
    }

    apply(spendingForm: NgForm) {
        if (this.fieldsAreEmpty(spendingForm)) {
            return;
        } else if (spendingForm.valid) {
            const title = spendingForm.value.title;
            const enteredAmount = spendingForm.value.amount;
            const formattedAmount =
                this.formattingHelperService.germanFormatToNumber(
                    enteredAmount
                );
            const amount = formattedAmount * -100;
            console.log('selected name & sum:', title, amount);

            this.applyChanges.emit({ title, amount });
            this.icon = '✔';
            this.message = 'PLAN.TAB_SPENT.MESSAGE_SUCCESS';
        } else {
            this.icon = '⚠';
            this.message = 'PLAN.TAB_SPENT.ERROR_MESSAGE.GENERAL';
        }
    }

    clearInput(event: Event): void {
        const input = event.target as HTMLInputElement;
        input.value = '';
        this.message = '';
        console.log('clearInput triggered');
        this.resetBalance.emit();
    }

    private fieldsAreEmpty(form: NgForm): boolean {
        if (!form.value.title || !form.value.amount) {
            this.icon = '⚠';
            this.message = 'PLAN.TAB_SPENT.ERROR_MESSAGE.INPUTS_INCOMPLETE';
            return true;
        }
        return false;
    }

    onSubmit() {
        console.log('Form submitted!');
    }
}

<form class="form-container" (ngSubmit)="onSubmit()" #spendingForm="ngForm">
    <div class="form-group">
        <label class="name-label" for="title">{{
            'PLAN.TAB_SPENT.NAME_LABEL' | translate
        }}</label>
        <input
            class="name-input"
            type="text"
            id="title"
            name="title"
            ngModel
            required
            pattern="^[a-zA-Z\s0-9\-.]+$"
            [title]="'PLAN.TAB_SPENT.INPUT_HINT.PRODUCT_INPUT' | translate"
            #title="ngModel"
            (blur)="formattingHelperService.formatNameInput($event)"
        />
    </div>

    <div class="form-group">
        <label class="amount-label" for="amount">{{
            'PLAN.TAB_SPENT.AMOUNT_LABEL' | translate
        }}</label>
        <input
            class="amount-input"
            type="text"
            id="amount"
            name="amount"
            ngModel
            required
            pattern="^\d{1,3}(?:\.\d{3})*(?:,\d{0,2})?$"
            [title]="'PLAN.TAB_SPENT.INPUT_HINT.AMOUNT_INPUT' | translate"
            translate
            #amount="ngModel"
            (blur)="formattingHelperService.formatAmountInput($event)"
            (focus)="clearInput($event)"
        />
    </div>

    <div class="button-group--plan-page">
        <button class="button" type="submit" (click)="calculate(spendingForm)">
            {{ 'PLAN.TAB_SPENT.BUTTON_LABEL.CALCULATE' | translate }}
        </button>
        <button class="button" type="submit" (click)="apply(spendingForm)">
            {{ 'PLAN.TAB_SPENT.BUTTON_LABEL.SUBMIT' | translate }}
        </button>
    </div>
</form>
<p *ngIf="title.invalid && title.dirty" class="error">
    {{ 'PLAN.TAB_SPENT.ERROR_MESSAGE.PRODUCT_INPUT' | translate }}
</p>
<p *ngIf="amount.invalid && amount.dirty" class="error">
    {{ 'PLAN.TAB_SPENT.ERROR_MESSAGE.AMOUNT_INPUT' | translate }}
</p>
<p *ngIf="message" class="message">
    <span class="message-icon" *ngIf="icon">{{ icon }}</span>
    {{ message | translate }}
</p>
