// assets/client/components/PageHeader.tsx
import LocaleSwitcher from '@/client/components/LocaleSwitcher';
import './PageHeader.scss';
import { useTranslation } from 'react-i18next';

interface Props {
  title?: string;
  isLoggedIn: boolean;
  backButtonTarget?: string;
}

export default function PageHeader({
  title,
  isLoggedIn,
  backButtonTarget,
}: Props) {
  const { t } = useTranslation();
  return (
    <>
      <nav className="navbar navbar-light bg-light">
        <div className="container-fluid d-flex justify-content-between align-items-center">
          <div className="d-flex justify-content-start align-items-center">
            {backButtonTarget ? (
              <a
                href={backButtonTarget}
                className="btn btn-link"
                title={t('PAGE_HEADER.BUTTONS.GO_TO_ACCOUNT_SELECTION')}
              >
                <img
                  src="/assets/images/go-back-arrow_small.png"
                  width={50}
                  height={50}
                  alt="Go back arrow"
                />
              </a>
            ) : (
              <div className="pseudo-element" />
            )}
          </div>

          <div className="d-flex justify-content-center">
            <div className="d-flex align-items-center">
              <div className="page-title navbar-text">{title}</div>
            </div>
          </div>

          <div className="d-flex justify-content-end align-items-center">
            <div>
              <LocaleSwitcher />
            </div>
            {isLoggedIn && (
              <a href="/logout" title={t('PAGE_HEADER.BUTTONS.LOGOUT')}>
                <img
                  src="/assets/images/logout-round-grey_small.png"
                  alt="logout button"
                  width={50}
                  height={50}
                  className="image-50x50"
                />
              </a>
            )}
          </div>
        </div>
      </nav>
    </>
  );
}

// assets/client/app/components/page-header/page-header.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { AccountService } from '../../app/services/account.service';
import { distinctUntilChanged, Observable, Subject } from 'rxjs';
import { Account } from '../../app/types/account';
import { TranslateService } from '@ngx-translate/core';
import { RoutePath } from '../../app/enum/routepath';
import { RouterService } from '../../app/services/router.service';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
    selector: 'money-sprouts-page-header',
    templateUrl: './page-header.component.html',
    styleUrls: ['./page-header.component.scss'],
})
export class PageHeaderComponent implements OnInit, OnDestroy {
    childClass: string = '';
    name: string = '';
    account$: Observable<Account | null>;
    urlSegment: string = '';
    logout = 'Logout';
    avatar: string = '';
    id: number = 0;
    isLoading = false;

    private destroy$ = new Subject<void>();

    constructor(
        private readonly router: RouterService,
        public accountService: AccountService,
        public translate: TranslateService,
        private router: Router
    ) {
        this.accountService.loading.subscribe((loading) => {
            this.isLoading = loading;
        });
        this.account$ = this.accountService.currentAccount$;
    }

    ngOnInit() {
        this.router.events
            .pipe(filter((event) => event instanceof NavigationEnd))
            .subscribe(() => {
                const segments = this.router.url.split('/');
                this.urlSegment = segments[segments.length - 1];
            });

        this.account$.subscribe((account) => {
            if (account) {
                this.name = account.name;
                this.avatar = account.avatar;
                this.id = account.id;
            }
        });
    }

    goBack() {
        if (this.urlSegment === 'dashboard') {
            this.router.navigateToRoute(RoutePath.AccountSelection);
        } else if (
            this.urlSegment === 'history' ||
            this.urlSegment === 'plan' ||
            this.urlSegment === 'overview'
        ) {
            this.router.navigateToDashboard(this.name);
        } else {
            return;
        }
    }

    isOnAccountSelectionPage(): boolean {
        return this.urlSegment === RoutePath.AccountSelection;
    }

    goToAccountSelection() {
        this.router.navigateToRoute(RoutePath.AccountSelection);
    }

    get pageTitle(): string {
        const pageName = this.router.getURL().split('/')[3];
        switch (pageName) {
            case 'dashboard':
                return 'PAGE_HEADER.PAGE_NAME.DASHBOARD';
            case 'overview':
                return 'PAGE_HEADER.PAGE_NAME.OVERVIEW';
            case 'history':
                return 'PAGE_HEADER.PAGE_NAME.HISTORY';
            case 'plan':
                return 'PAGE_HEADER.PAGE_NAME.PLAN';
            default:
                return '';
        }
    }

    get welcomeTitle(): string {
        return 'PAGE_HEADER.PAGE_NAME.ACCOUNT-SELECTION';
    }

    onLogout(event: Event) {
        event.preventDefault();
        this.accountService.logoutOrDeselectAccount();
        this.router.navigateToRoute(RoutePath.Logout);
    }

    ngOnDestroy(): void {
        this.destroy$.next();
        this.destroy$.complete();
    }
}

<nav class="navbar navbar-light bg-light">
    <div
        class="container-fluid d-flex justify-content-between align-items-center"
    >
        <div
            *ngIf="!isOnAccountSelectionPage(); else pseudoElement"
            class="d-flex justify-content-start align-items-center"
        >
            <button
                class="btn btn-link"
                (click)="goBack()"
                [title]="'PAGE_HEADER.BUTTONS.GO_BACK' | translate"
            >
                <img
                    src="/assets/images/go-back-arrow_small.png"
                    alt="Go back arrow"
                    class="image-50x50"
                />
            </button>
        </div>
        <ng-template #pseudoElement>
            <div class="pseudo-element"></div>
        </ng-template>

        <div
            class="d-flex justify-content-center"
            *ngIf="!isOnAccountSelectionPage(); else onAccountSelectionPage"
        >
            <div class="d-flex align-items-center">
                <button
                    *ngIf="!isLoading"
                    class="btn btn-link"
                    (click)="goToAccountSelection()"
                    [title]="
                        'PAGE_HEADER.BUTTONS.GO_TO_ACCOUNT_SELECTION'
                            | translate
                    "
                >
                    <img
                        [src]="
                            accountService.getAvatarForAccount(account$ | async)
                        "
                        alt="Account avatar"
                        class="image-50x50"
                    />
                </button>

                <div class="navbar-text page-title">
                    {{ pageTitle | translate }}
                </div>
            </div>
        </div>
        <ng-template #onAccountSelectionPage>
            <div class="navbar-text added-padding-left page-title">
                {{ welcomeTitle | translate }}
            </div>
        </ng-template>

        <div *ngIf="isOnAccountSelectionPage()" class="pseudo-element"></div>

        <div class="d-flex justify-content-end align-items-center">
            <div>
                <money-sprouts-multilanguage></money-sprouts-multilanguage>
            </div>
            <a
                href="/logout"
                (click)="onLogout($event)"
                class="btn btn-link"
                [title]="'PAGE_HEADER.BUTTONS.LOGOUT' | translate"
            >
                <img
                    src="assets/images/logout-round-grey_small.png"
                    alt="logout button"
                    class="image-50x50"
                />
            </a>
        </div>
    </div>
</nav>
